### ISSUE TITLE
add support for `import-url`

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc-gdrive#18]
> With iterative/PyDrive2#113 closed, would it be possible to resume GDrive support for import-url?

As far as I can tell, everything should be there for import-url, so let's create another issue to finalize the support / add it docs etc. (if I am not missing something)

_Originally posted by @isidentical in https://github.com/iterative/dvc/issues/2865#issuecomment-929263156_

**Comment by shcheklein** [comment]
It's now seems to be supported:

dvc import-url gdrive://1n-2czSzZ-KeWzW-vqZ5A2wz0oe0uxOCZ/file.png file.png

or 

dvc import-url remote://storage1/file.png file.png

where storage1 is defined like this:

```
['remote "storage1"']
    url = gdrive://1n-2czSzZ-KeWzW-vqZ5A2wz0oe0uxOCZ
```
